export function toolSoftwareLinux() {
    return [
        {
            collapsible: true,
            text: '文件操作',
            items: [
                { text: 'cat 命令', link: '/toolSoftware/Linux/' },
                { text: 'cp 命令', link: '/toolSoftware/Linux/cp命令' },
                { text: 'mv 命令', link: '/toolSoftware/Linux/mv命令' },
                { text: 'rm 命令', link: '/toolSoftware/Linux/rm命令' },
                { text: 'touch 命令', link: '/toolSoftware/Linux/touch命令' },
                { text: 'ln 命令', link: '/toolSoftware/Linux/ln命令' },
                { text: 'find 命令', link: '/toolSoftware/Linux/find命令' },
                { text: 'locate 命令', link: '/toolSoftware/Linux/locate命令' },
                { text: 'whereis 命令', link: '/toolSoftware/Linux/whereis命令' },
                { text: 'which 命令', link: '/toolSoftware/Linux/which命令' },
            ],
        },
        {
            collapsible: true,
            text: '文件权限',
            items: [
                { text: 'chmod 命令', link: '/toolSoftware/Linux/chmod命令' },
                { text: 'chown 命令', link: '/toolSoftware/Linux/chown命令' },
                { text: 'chattr 命令', link: '/toolSoftware/Linux/chattr命令' },
                { text: 'lsattr 命令', link: '/toolSoftware/Linux/lsattr命令' },
                { text: 'umask 命令', link: '/toolSoftware/Linux/umask命令' },
            ],
        },
        {
            collapsible: true,
            text: '文本处理',
            items: [
                { text: 'grep 命令', link: '/toolSoftware/Linux/grep命令' },
                { text: 'egrep 命令', link: '/toolSoftware/Linux/egrep命令' },
                { text: 'fgrep 命令', link: '/toolSoftware/Linux/fgrep命令' },
                { text: 'awk 命令', link: '/toolSoftware/Linux/awk命令' },
                { text: 'sed 命令', link: '/toolSoftware/Linux/sed命令' },
                { text: 'cut 命令', link: '/toolSoftware/Linux/cut命令' },
                { text: 'paste 命令', link: '/toolSoftware/Linux/paste命令' },
                { text: 'sort 命令', link: '/toolSoftware/Linux/sort命令' },
                { text: 'uniq 命令', link: '/toolSoftware/Linux/uniq命令' },
                { text: 'tr 命令', link: '/toolSoftware/Linux/tr命令' },
                { text: 'fmt 命令', link: '/toolSoftware/Linux/fmt命令' },
                { text: 'fold 命令', link: '/toolSoftware/Linux/fold命令' },
                { text: 'col 命令', link: '/toolSoftware/Linux/col命令' },
                { text: 'colrm 命令', link: '/toolSoftware/Linux/colrm命令' },
                { text: 'aspell 命令', link: '/toolSoftware/Linux/aspell命令' },
            ],
        },
        {
            collapsible: true,
            text: '文件比较与合并',
            items: [
                { text: 'diff 命令', link: '/toolSoftware/Linux/diff命令' },
                { text: 'diffstat 命令', link: '/toolSoftware/Linux/diffstat命令' },
                { text: 'cmp 命令', link: '/toolSoftware/Linux/cmp命令' },
                { text: 'comm 命令', link: '/toolSoftware/Linux/comm命令' },
                { text: 'join 命令', link: '/toolSoftware/Linux/join命令' },
                { text: 'patch 命令', link: '/toolSoftware/Linux/patch命令' },
            ],
        },
        {
            collapsible: true,
            text: '文件分割与处理',
            items: [
                { text: 'split 命令', link: '/toolSoftware/Linux/split命令' },
                { text: 'csplit 命令', link: '/toolSoftware/Linux/csplit命令' },
                { text: 'expr 命令', link: '/toolSoftware/Linux/expr命令' },
                { text: 'look 命令', link: '/toolSoftware/Linux/look命令' },
            ],
        },
        {
            collapsible: true,
            text: '进程管理',
            items: [
                { text: 'ps 命令', link: '/toolSoftware/Linux/ps命令' },
                { text: 'top 命令', link: '/toolSoftware/Linux/top命令' },
                { text: 'kill 命令', link: '/toolSoftware/Linux/kill命令' },
                { text: 'systemctl 命令', link: '/toolSoftware/Linux/systemctl命令' },
                { text: 'journalctl 命令', link: '/toolSoftware/Linux/journalctl命令' },
            ],
        },
        {
            collapsible: true,
            text: '网络管理',
            items: [
                { text: 'ifconfig 命令', link: '/toolSoftware/Linux/ifconfig命令' },
                { text: 'ip 命令', link: '/toolSoftware/Linux/ip命令' },
                { text: 'netstat 命令', link: '/toolSoftware/Linux/netstat命令' },
                { text: 'route 命令', link: '/toolSoftware/Linux/route命令' },
                { text: 'traceroute 命令', link: '/toolSoftware/Linux/traceroute命令' },
                { text: 'curl 命令', link: '/toolSoftware/Linux/curl命令' },
            ],
        },
        {
            collapsible: true,
            text: '远程传输',
            items: [
                { text: 'scp 命令', link: '/toolSoftware/Linux/scp命令' },
                { text: 'rcp 命令', link: '/toolSoftware/Linux/rcp命令' },
            ],
        },
        {
            collapsible: true,
            text: '文件查看',
            items: [
                { text: 'more 命令', link: '/toolSoftware/Linux/more命令' },
                { text: 'less 命令', link: '/toolSoftware/Linux/less命令' },
                { text: 'od 命令', link: '/toolSoftware/Linux/od命令' },
                { text: 'file 命令', link: '/toolSoftware/Linux/file命令' },
            ],
        },
        {
            collapsible: true,
            text: '系统工具',
            items: [
                { text: 'mktemp 命令', link: '/toolSoftware/Linux/mktemp命令' },
                { text: 'tmpwatch 命令', link: '/toolSoftware/Linux/tmpwatch命令' },
                { text: 'tee 命令', link: '/toolSoftware/Linux/tee命令' },
                { text: 'read 命令', link: '/toolSoftware/Linux/read命令' },
                { text: 'updatedb 命令', link: '/toolSoftware/Linux/updatedb命令' },
                { text: 'mc 命令', link: '/toolSoftware/Linux/mc命令' },
            ],
        },
        {
            collapsible: true,
            text: '编辑器',
            items: [
                { text: 'ed 命令', link: '/toolSoftware/Linux/ed命令' },
                { text: 'ex 命令', link: '/toolSoftware/Linux/ex命令' },
                { text: 'pico 命令', link: '/toolSoftware/Linux/pico命令' },
            ],
        },
    ]
}