export function frontendJavascript() {
    return [
        {
            //开启折叠
            collapsible: true,
            text: '第一章',
            items: [
                { text: '常见的内存泄漏场景', link: '/frontend/JavaScript/' },
                { text: '防抖与节流', link: '/frontend/JavaScript/防抖与节流' },
                { text: '函数声明与函数表达式', link: '/frontend/JavaScript/函数声明与函数表达式' },
                { text: '函数式编程的理解', link: '/frontend/JavaScript/函数式编程的理解' },
                { text: '模板语法的简单实现', link: '/frontend/JavaScript/模板语法的简单实现' },
                { text: '匿名函数与自执行函数', link: '/frontend/JavaScript/匿名函数与自执行函数' },
                { text: '深入理解Js数组', link: '/frontend/JavaScript/深入理解Js数组' },
                { text: '深入理解Js中的this', link: '/frontend/JavaScript/深入理解Js中的this' },
                { text: '实现浅拷贝与深拷贝', link: '/frontend/JavaScript/实现浅拷贝与深拷贝' },
                { text: '事件冒泡及阻止', link: '/frontend/JavaScript/事件冒泡及阻止' },
            ],
        },
        {
            //开启折叠
            collapsible: true,
            text: '第二章',
            items: [
                { text: '手动实现AJAX', link: '/frontend/JavaScript/手动实现AJAX' },
                { text: '手动实现apply call bind', link: '/frontend/JavaScript/手动实现apply call bind' },
                { text: '手动实现Promise', link: '/frontend/JavaScript/手动实现Promise' },
                { text: '原型与原型链', link: '/frontend/JavaScript/原型与原型链' },
                { text: '作用域与作用域链', link: '/frontend/JavaScript/作用域与作用域链' },
                { text: 'apply、call、bind', link: '/frontend/JavaScript/apply、call、bind' },
                { text: 'async、await', link: '/frontend/JavaScript/async、await' },
                { text: 'async、await剖析', link: '/frontend/JavaScript/async、await剖析' },
                { text: 'defineProperty', link: '/frontend/JavaScript/defineProperty' },
                { text: 'ES6新特性', link: '/frontend/JavaScript/ES6新特性' },
                { text: 'Function与Object', link: '/frontend/JavaScript/Function与Object' },
                { text: 'Generator函数', link: '/frontend/JavaScript/Generator函数' },
                { text: 'getter与setter', link: '/frontend/JavaScript/getter与setter' },
                { text: 'JavaScript闭包', link: '/frontend/JavaScript/JavaScript闭包' },
                { text: 'JavaScript选择器', link: '/frontend/JavaScript/JavaScript选择器' },
                { text: 'JavaScript异步机制', link: '/frontend/JavaScript/JavaScript异步机制' },
                { text: 'JS变量提升', link: '/frontend/JavaScript/JS变量提升' },
                { text: 'Js遍历对象总结', link: '/frontend/JavaScript/Js遍历对象总结' },
                { text: 'Js遍历数组总结', link: '/frontend/JavaScript/Js遍历数组总结' },
                { text: 'Js捕获异常的方法', link: '/frontend/JavaScript/Js捕获异常的方法' },
                { text: 'Js常见手写题总结', link: '/frontend/JavaScript/Js常见手写题总结' },
                { text: 'Js创建对象的方式', link: '/frontend/JavaScript/Js创建对象的方式' },
                { text: 'Js的GC机制', link: '/frontend/JavaScript/Js的GC机制' },
                { text: 'Js获取数据类型', link: '/frontend/JavaScript/Js获取数据类型' },
                { text: 'Js继承的实现方式', link: '/frontend/JavaScript/Js继承的实现方式' },
                { text: 'Js箭头函数', link: '/frontend/JavaScript/Js箭头函数' },
                { text: 'Js将字符串转数字的方式', link: '/frontend/JavaScript/Js将字符串转数字的方式' },
        
            ],
        },
        {
            //开启折叠
            collapsible: true,
            text: '第三章',
            items: [
                { text: 'Js模块化导入导出', link: '/frontend/JavaScript/Js模块化导入导出' },
                { text: 'Js模块化开发的理解', link: '/frontend/JavaScript/Js模块化开发的理解' },
                { text: 'Js实现链表操作', link: '/frontend/JavaScript/Js实现链表操作' },
                { text: 'Js实现数组排序', link: '/frontend/JavaScript/Js实现数组排序' },
                { text: 'Js实用小技巧', link: '/frontend/JavaScript/Js实用小技巧' },
                { text: 'JS事件流模型', link: '/frontend/JavaScript/JS事件流模型' },
                { text: 'Js数组操作', link: '/frontend/JavaScript/Js数组操作' },
                { text: 'Js文件异步加载', link: '/frontend/JavaScript/Js文件异步加载' },
                { text: 'Js严格模式', link: '/frontend/JavaScript/Js严格模式' },
                { text: 'Js中==与===', link: '/frontend/JavaScript/Js中==与===' },
                { text: 'Js中的堆栈', link: '/frontend/JavaScript/Js中的堆栈' },
                { text: 'Js中的逻辑运算符', link: '/frontend/JavaScript/Js中的逻辑运算符' },
                { text: 'Js中的位操作符', link: '/frontend/JavaScript/Js中的位操作符' },
                { text: 'Js中数组空位问题', link: '/frontend/JavaScript/Js中数组空位问题' },
                { text: 'Js中Array对象', link: '/frontend/JavaScript/Js中Array对象' },
                { text: 'Js中Currying的应用', link: '/frontend/JavaScript/Js中Currying的应用' },
                { text: 'Js中Date对象', link: '/frontend/JavaScript/Js中Date对象' },
                { text: 'Js中fetch方法', link: '/frontend/JavaScript/Js中fetch方法' },
                { text: 'Js中Math对象', link: '/frontend/JavaScript/Js中Math对象' },
                { text: 'Js中Proxy对象', link: '/frontend/JavaScript/Js中Proxy对象' },
                { text: 'Js中Reflect对象', link: '/frontend/JavaScript/Js中Reflect对象' },
                { text: 'Js中RegExp对象', link: '/frontend/JavaScript/Js中RegExp对象' },
                { text: 'Js中String对象', link: '/frontend/JavaScript/Js中String对象' },
                { text: 'Js中Symbol对象', link: '/frontend/JavaScript/Js中Symbol对象' },
                { text: 'Json Web Token', link: '/frontend/JavaScript/Json Web Token' },
            ],
        },
        {
            //开启折叠
            collapsible: true,
            text: '第四章',
            items: [
                { text: 'let与const', link: '/frontend/JavaScript/let与const' },
                { text: 'Map与WeakMap', link: '/frontend/JavaScript/Map与WeakMap' },
                { text: 'new运算符', link: '/frontend/JavaScript/new运算符' },
                { text: 'null和undefined的区别', link: '/frontend/JavaScript/null和undefined的区别' },
                { text: 'Object对象', link: '/frontend/JavaScript/Object对象' },
                { text: 'Promise对象', link: '/frontend/JavaScript/Promise对象' },
                { text: 'Set与WeakSet', link: '/frontend/JavaScript/Set与WeakSet' },
                { text: 'Thunk函数的使用', link: '/frontend/JavaScript/Thunk函数的使用' },
                { text: 'valueOf与toString', link: '/frontend/JavaScript/valueOf与toString' },
                { text: 'XML和JSON的比较', link: '/frontend/JavaScript/XML和JSON的比较' },

            ],
        },
    ]
}