export function frontendJavascript() {
    return [
        {
            collapsible: true,
            text: 'JavaScript 基础',
            items: [
                { text: '常见的内存泄漏场景', link: '/frontend/JavaScript/' },
                { text: 'Js 严格模式', link: '/frontend/JavaScript/Js严格模式' },
                { text: 'Js 变量提升', link: '/frontend/JavaScript/JS变量提升' },
                { text: 'Js 获取数据类型', link: '/frontend/JavaScript/Js获取数据类型' },
                { text: 'Js 中的堆栈', link: '/frontend/JavaScript/Js中的堆栈' },
                { text: 'Js 中的逻辑运算符', link: '/frontend/JavaScript/Js中的逻辑运算符' },
                { text: 'Js 中的位操作符', link: '/frontend/JavaScript/Js中的位操作符' },
                { text: 'Js 中==与===', link: '/frontend/JavaScript/Js中全等' },
                { text: 'null 和 undefined 的区别', link: '/frontend/JavaScript/null和undefined的区别' },
            ],
        },
        {
            collapsible: true,
            text: '函数与作用域',
            items: [
                { text: '函数声明与函数表达式', link: '/frontend/JavaScript/函数声明与函数表达式' },
                { text: '匿名函数与自执行函数', link: '/frontend/JavaScript/匿名函数与自执行函数' },
                { text: 'JavaScript 闭包', link: '/frontend/JavaScript/JavaScript闭包' },
                { text: '作用域与作用域链', link: '/frontend/JavaScript/作用域与作用域链' },
                { text: '深入理解 Js 中的 this', link: '/frontend/JavaScript/深入理解Js中的this' },
                { text: 'apply、call、bind', link: '/frontend/JavaScript/apply、call、bind' },
                { text: '手动实现 apply call bind', link: '/frontend/JavaScript/手动实现apply call bind' },
                { text: 'Js 箭头函数', link: '/frontend/JavaScript/Js箭头函数' },
                { text: '函数式编程的理解', link: '/frontend/JavaScript/函数式编程的理解' },
                { text: 'Js 中 Currying 的应用', link: '/frontend/JavaScript/Js中Currying的应用' },
                { text: 'Thunk 函数的使用', link: '/frontend/JavaScript/Thunk函数的使用' },
            ],
        },
        {
            collapsible: true,
            text: '对象与原型',
            items: [
                { text: 'Js 创建对象的方式', link: '/frontend/JavaScript/Js创建对象的方式' },
                { text: 'Js 继承的实现方式', link: '/frontend/JavaScript/Js继承的实现方式' },
                { text: '原型与原型链', link: '/frontend/JavaScript/原型与原型链' },
                { text: 'Function 与 Object', link: '/frontend/JavaScript/Function与Object' },
                { text: 'Object 对象', link: '/frontend/JavaScript/Object对象' },
                { text: 'new 运算符', link: '/frontend/JavaScript/new运算符' },
                { text: 'getter 与 setter', link: '/frontend/JavaScript/getter与setter' },
                { text: 'defineProperty', link: '/frontend/JavaScript/defineProperty' },
                { text: 'Js 中 Proxy 对象', link: '/frontend/JavaScript/Js中Proxy对象' },
                { text: 'Js 中 Reflect 对象', link: '/frontend/JavaScript/Js中Reflect对象' },
                { text: 'Js 中 Symbol 对象', link: '/frontend/JavaScript/Js中Symbol对象' },
                { text: 'valueOf 与 toString', link: '/frontend/JavaScript/valueOf与toString' },
            ],
        },
        {
            collapsible: true,
            text: '数据结构与集合',
            items: [
                { text: '深入理解 Js 数组', link: '/frontend/JavaScript/深入理解Js数组' },
                { text: 'Js 中 Array 对象', link: '/frontend/JavaScript/Js中Array对象' },
                { text: 'Js 数组操作', link: '/frontend/JavaScript/Js数组操作' },
                { text: 'Js 遍历数组总结', link: '/frontend/JavaScript/Js遍历数组总结' },
                { text: 'Js 遍历对象总结', link: '/frontend/JavaScript/Js遍历对象总结' },
                { text: 'Js 中数组空位问题', link: '/frontend/JavaScript/Js中数组空位问题' },
                { text: 'Js 实现数组排序', link: '/frontend/JavaScript/Js实现数组排序' },
                { text: 'Js 实现链表操作', link: '/frontend/JavaScript/Js实现链表操作' },
                { text: 'Map 与 WeakMap', link: '/frontend/JavaScript/Map与WeakMap' },
                { text: 'Set 与 WeakSet', link: '/frontend/JavaScript/Set与WeakSet' },
            ],
        },
        {
            collapsible: true,
            text: '异步编程',
            items: [
                { text: 'JavaScript 异步机制', link: '/frontend/JavaScript/JavaScript异步机制' },
                { text: 'Promise 对象', link: '/frontend/JavaScript/Promise对象' },
                { text: '手动实现 Promise', link: '/frontend/JavaScript/手动实现Promise' },
                { text: 'async、await', link: '/frontend/JavaScript/async、await' },
                { text: 'async、await 剖析', link: '/frontend/JavaScript/async、await剖析' },
                { text: 'Generator 函数', link: '/frontend/JavaScript/Generator函数' },
                { text: '手动实现 AJAX', link: '/frontend/JavaScript/手动实现AJAX' },
                { text: 'Js 中 fetch 方法', link: '/frontend/JavaScript/Js中fetch方法' },
                { text: 'Js 文件异步加载', link: '/frontend/JavaScript/Js文件异步加载' },
            ],
        },
        {
            collapsible: true,
            text: 'ES6+ 新特性',
            items: [
                { text: 'ES6 新特性', link: '/frontend/JavaScript/ES6新特性' },
                { text: 'let 与 const', link: '/frontend/JavaScript/let与const' },
                { text: 'Js 模块化开发的理解', link: '/frontend/JavaScript/Js模块化开发的理解' },
                { text: 'Js 模块化导入导出', link: '/frontend/JavaScript/Js模块化导入导出' },
            ],
        },
        {
            collapsible: true,
            text: '事件与 DOM',
            items: [
                { text: 'JS 事件流模型', link: '/frontend/JavaScript/JS事件流模型' },
                { text: '事件冒泡及阻止', link: '/frontend/JavaScript/事件冒泡及阻止' },
                { text: 'JavaScript 选择器', link: '/frontend/JavaScript/JavaScript选择器' },
                { text: '防抖与节流', link: '/frontend/JavaScript/防抖与节流' },
            ],
        },
        {
            collapsible: true,
            text: '内置对象',
            items: [
                { text: 'Js 中 Date 对象', link: '/frontend/JavaScript/Js中Date对象' },
                { text: 'Js 中 Math 对象', link: '/frontend/JavaScript/Js中Math对象' },
                { text: 'Js 中 String 对象', link: '/frontend/JavaScript/Js中String对象' },
                { text: 'Js 中 RegExp 对象', link: '/frontend/JavaScript/Js中RegExp对象' },
                { text: 'Js 将字符串转数字的方式', link: '/frontend/JavaScript/Js将字符串转数字的方式' },
            ],
        },
        {
            collapsible: true,
            text: '数据格式与通信',
            items: [
                { text: 'Json Web Token', link: '/frontend/JavaScript/Json Web Token' },
                { text: 'XML 和 JSON 的比较', link: '/frontend/JavaScript/XML和JSON的比较' },
            ],
        },
        {
            collapsible: true,
            text: '高级技巧',
            items: [
                { text: '实现浅拷贝与深拷贝', link: '/frontend/JavaScript/实现浅拷贝与深拷贝' },
                { text: '模板语法的简单实现', link: '/frontend/JavaScript/模板语法的简单实现' },
                { text: 'Js 实用小技巧', link: '/frontend/JavaScript/Js实用小技巧' },
                { text: 'Js 捕获异常的方法', link: '/frontend/JavaScript/Js捕获异常的方法' },
                { text: 'Js 的 GC 机制', link: '/frontend/JavaScript/Js的GC机制' },
                { text: 'Js 常见手写题总结', link: '/frontend/JavaScript/Js常见手写题总结' },
            ],
        },
    ]
}